columns:
  - _id: object
  - customerID: object
  - gender: object
  - SeniorCitizen: int
  - Partner: object
  - Dependents: object
  - tenure: int
  - PhoneService: object
  - MultipleLines: object
  - InternetService: object
  - OnlineSecurity: object
  - OnlineBackup: object
  - DeviceProtection: object
  - TechSupport: object
  - StreamingTV: object
  - StreamingMovies: object
  - Contract: object
  - PaperlessBilling: object
  - PaymentMethod: object
  - MonthlyCharges: float
  - TotalCharges: float
  - Churn: object

numerical_columns:
  - SeniorCitizen
  - tenure
  - MonthlyCharges
  - TotalCharges

categorical_columns:
  - gender
  - Partner
  - Dependents
  - PhoneService
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod
  - Churn

drop_columns:
  - _id
  - customerID

# for data transformation
num_features:
  - tenure
  - MonthlyCharges

mm_columns:
  - TotalCharges